"""
Hybrid Quantum Machine Learning Platform for Early Brain Tumor Detection
------------------------------------------------------------------------
Module: Classical SVM Baseline Classifier

RESEARCH USE ONLY:
This module is developed strictly as an experimental machine learning research
baseline for benchmarking classical vs. quantum models on brain MRI feature
representations. It is NOT intended, validated, or certified for clinical diagnosis,
patient triage, or medical decision-making.

Purpose:
- Loads the standardized 4-dimensional PCA features generated by the preprocessing pipeline.
- Trains a Support Vector Machine (SVM) classifier with an RBF kernel.
  * Kernel Justification: The Radial Basis Function (RBF) kernel is chosen because
    complex biomedical imaging features after PCA projection typically exhibit non-linear
    separation boundaries. The RBF kernel maps inputs into an infinite-dimensional feature
    space, offering high expressive power and serving as a direct classical benchmark
    to quantum Hilbert-space kernel methods (Quantum VQC / Quantum Kernels).
- Evaluates performance using Accuracy, Precision, Recall/Sensitivity, Specificity, and F1-score.
- Generates and saves a confusion matrix visualization and serialized model artifact.
- Measures training latency and per-sample inference latency.
"""

import os
import sys

# Configure environment before importing matplotlib
os.environ["MPLCONFIGDIR"] = "/tmp"

import json
import time
import pickle
from pathlib import Path

import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.svm import SVC
from sklearn.metrics import (
    accuracy_score,
    precision_recall_fscore_support,
    confusion_matrix
)


def load_preprocessed_data(data_dir: str = "processed_data"):
    """
    Step 1: Loads preprocessed 4D PCA training and testing sets and metadata.
    Ensures exact data parity with future Quantum VQC models.
    """
    path = Path(data_dir)
    if not path.exists():
        raise FileNotFoundError(
            f"Preprocessed data directory '{data_dir}' not found. "
            f"Please run 'preprocess.py' first."
        )

    X_train = np.load(path / "X_train_pca.npy")
    X_test = np.load(path / "X_test_pca.npy")
    y_train = np.load(path / "y_train.npy")
    y_test = np.load(path / "y_test.npy")

    with open(path / "metadata.json", "r") as f:
        metadata = json.load(f)

    # Class mappings: ensure integer string keys are properly mapped
    class_map = {int(k): v for k, v in metadata["classes"].items()}
    class_names = [class_map[i] for i in range(len(class_map))]

    return X_train, X_test, y_train, y_test, class_names, metadata


def calculate_multiclass_specificity(cm: np.ndarray) -> tuple[dict[int, float], float]:
    """
    Calculates per-class and macro-averaged Specificity (True Negative Rate)
    using One-vs-Rest formulation for multiclass confusion matrices.
    
    Formula per class i:
      TN_i = Total_samples - (TP_i + FP_i + FN_i)
      Specificity_i = TN_i / (TN_i + FP_i)
    """
    num_classes = cm.shape[0]
    total_samples = np.sum(cm)
    per_class_specificity = {}

    for i in range(num_classes):
        tp = cm[i, i]
        fp = np.sum(cm[:, i]) - tp
        fn = np.sum(cm[i, :]) - tp
        tn = total_samples - (tp + fp + fn)

        spec = tn / (tn + fp) if (tn + fp) > 0 else 0.0
        per_class_specificity[i] = float(spec)

    macro_specificity = float(np.mean(list(per_class_specificity.values())))
    return per_class_specificity, macro_specificity


def train_and_evaluate_svm(
    data_dir: str = "processed_data",
    output_dir: str = "results",
    model_dir: str = "models",
    c_param: float = 1.0,
    gamma: str = "scale"
):
    """
    Trains the classical SVM model, evaluates metrics, and saves artifacts.
    """
    out_path = Path(output_dir)
    mod_path = Path(model_dir)
    out_path.mkdir(parents=True, exist_ok=True)
    mod_path.mkdir(parents=True, exist_ok=True)

    # 1. Load Data
    print("\n" + "=" * 68)
    print("  CLASSICAL SVM BASELINE: BRAIN TUMOR CLASSIFICATION (RESEARCH ONLY)")
    print("=" * 68)
    X_train, X_test, y_train, y_test, class_names, meta = load_preprocessed_data(data_dir)
    print(f" Loaded {len(X_train)} training samples and {len(X_test)} testing samples.")
    print(f" Feature Dimension : {X_train.shape[1]} (4-dimensional PCA features)")
    print(f" Target Classes    : {class_names}")

    # 2. Configure and Train SVM
    # Kernel Justification: The Radial Basis Function (RBF) kernel is chosen because
    # complex biomedical imaging features after PCA projection typically exhibit non-linear
    # separation boundaries. The RBF kernel maps inputs into an infinite-dimensional feature
    # space, offering high expressive power and serving as a direct classical benchmark
    # to quantum Hilbert-space kernel methods (Quantum VQC / Quantum Kernels).
    svm_classifier = SVC(
        C=c_param,
        kernel="rbf",
        gamma=gamma,
        random_state=42
    )

    print("\n[STEP 1] Training Classical Support Vector Classifier (RBF Kernel)...")
    train_start = time.perf_counter()
    svm_classifier.fit(X_train, y_train)
    train_duration = time.perf_counter() - train_start
    print(f"         Training completed in: {train_duration * 1000:.2f} ms")

    # 3. Generate Predictions and Measure Latency
    print("[STEP 2] Evaluating on the held-out test partition...")
    pred_start = time.perf_counter()
    y_pred = svm_classifier.predict(X_test)
    pred_duration = time.perf_counter() - pred_start
    per_sample_latency = (pred_duration / len(X_test)) * 1000

    # 4. Compute Evaluation Metrics
    accuracy = float(accuracy_score(y_test, y_pred))
    precision_macro, recall_macro, f1_macro, _ = precision_recall_fscore_support(
        y_test, y_pred, average="macro", zero_division=0
    )
    precision_weighted, recall_weighted, f1_weighted, _ = precision_recall_fscore_support(
        y_test, y_pred, average="weighted", zero_division=0
    )

    # Per-class precision, recall, f1
    prec_per_class, rec_per_class, f1_per_class, _ = precision_recall_fscore_support(
        y_test, y_pred, average=None, zero_division=0
    )

    # Confusion matrix & Specificity
    cm = confusion_matrix(y_test, y_pred)
    per_class_spec, macro_spec = calculate_multiclass_specificity(cm)

    # 5. Save Confusion Matrix Plot
    cm_plot_path = out_path / "confusion_matrix_svm.png"
    plt.figure(figsize=(7, 6), dpi=150)
    sns.heatmap(
        cm,
        annot=True,
        fmt="d",
        cmap="Blues",
        xticklabels=class_names,
        yticklabels=class_names,
        cbar=True,
        square=True
    )
    plt.title("Confusion Matrix - Classical SVM Baseline (RBF Kernel)", fontsize=12, fontweight="bold", pad=12)
    plt.xlabel("Predicted Class", fontsize=10, labelpad=8)
    plt.ylabel("True Class", fontsize=10, labelpad=8)
    plt.tight_layout()
    plt.savefig(cm_plot_path)
    plt.close()
    print(f"[STEP 3] Saved confusion matrix visualization to: {cm_plot_path}")

    # 6. Save Model Artifact
    model_save_path = mod_path / "svm_baseline_model.pkl"
    with open(model_save_path, "wb") as f:
        pickle.dump(svm_classifier, f)
    print(f"[STEP 4] Serialized trained SVM model to: {model_save_path}")

    # 7. Compile Evaluation Metrics Record
    metrics_record = {
        "model_type": "Classical Support Vector Machine (SVC)",
        "kernel": "rbf",
        "c_parameter": c_param,
        "gamma": gamma,
        "disclaimer": "Experimental research classification baseline only. Not for clinical diagnosis.",
        "input_features": "4D PCA of Classical MRI Features",
        "train_samples": int(len(X_train)),
        "test_samples": int(len(X_test)),
        "training_time_ms": float(train_duration * 1000),
        "total_inference_time_ms": float(pred_duration * 1000),
        "per_sample_inference_latency_ms": float(per_sample_latency),
        "overall_metrics": {
            "accuracy": float(accuracy),
            "macro_precision": float(precision_macro),
            "macro_recall_sensitivity": float(recall_macro),
            "macro_specificity": float(macro_spec),
            "macro_f1_score": float(f1_macro),
            "weighted_precision": float(precision_weighted),
            "weighted_recall": float(recall_weighted),
            "weighted_f1_score": float(f1_weighted)
        },
        "per_class_metrics": {
            class_names[i]: {
                "precision": float(prec_per_class[i]),
                "recall_sensitivity": float(rec_per_class[i]),
                "specificity": float(per_class_spec[i]),
                "f1_score": float(f1_per_class[i])
            }
            for i in range(len(class_names))
        },
        "confusion_matrix": cm.tolist()
    }

    metrics_save_path = out_path / "svm_metrics.json"
    with open(metrics_save_path, "w") as f:
        json.dump(metrics_record, f, indent=2)

    # 8. Print Clean Evaluation Report
    print_evaluation_summary(metrics_record, class_names)

    return metrics_record


def print_evaluation_summary(m: dict, class_names: list[str]):
    """
    Step 7: Prints formatted evaluation table and timing profile.
    """
    ov = m["overall_metrics"]
    print("\n" + "-" * 68)
    print("  EVALUATION METRICS SUMMARY (CLASSICAL SVM BASELINE)")
    print("-" * 68)
    print(f" Accuracy                 : {ov['accuracy'] * 100:6.2f}%")
    print(f" Macro Precision          : {ov['macro_precision'] * 100:6.2f}%")
    print(f" Macro Recall/Sensitivity : {ov['macro_recall_sensitivity'] * 100:6.2f}%")
    print(f" Macro Specificity        : {ov['macro_specificity'] * 100:6.2f}%")
    print(f" Macro F1-Score           : {ov['macro_f1_score'] * 100:6.2f}%")
    print(f" Weighted F1-Score        : {ov['weighted_f1_score'] * 100:6.2f}%")

    print("\n Per-Class Performance Breakdown:")
    header = f" {'Class Name':<14} | {'Precision':<10} | {'Recall/Sens':<12} | {'Specificity':<12} | {'F1-Score':<10}"
    print(header)
    print(" " + "-" * len(header))
    for cname in class_names:
        c = m["per_class_metrics"][cname]
        print(f" {cname:<14} | {c['precision']*100:8.2f}% | {c['recall_sensitivity']*100:10.2f}% | {c['specificity']*100:10.2f}% | {c['f1_score']*100:8.2f}%")

    print("\n Computational Benchmarks:")
    print(f" • Training Duration        : {m['training_time_ms']:6.2f} ms")
    print(f" • Total Test Inference Time: {m['total_inference_time_ms']:6.2f} ms ({m['test_samples']} samples)")
    print(f" • Latency per Sample       : {m['per_sample_inference_latency_ms']:6.4f} ms/sample")

    print("\n Research Artifacts Stored:")
    print(" • Trained Model            : models/svm_baseline_model.pkl")
    print(" • Confusion Matrix Graphic : results/confusion_matrix_svm.png")
    print(" • Detailed JSON Metrics    : results/svm_metrics.json")
    print("=" * 68 + "\n")


if __name__ == "__main__":
    train_and_evaluate_svm()
